### ISSUE TITLE
ChatAttachment class improvement suggestion

### ISSUE THREAD

**Issue by LeeHyKu** [storycraft/node-kakao#44]
**current code**
```
export class ChatAttachment {
  readAttachment(json:any):void
```
**how to use**
```
let a = new ChatAttachment();
a.readAttachment(JSON);
chat.replyTemplate(new AttachmentTemplate(a));
```

if **readAttachment** function returns 'this' or **ChatAttachment** class has 'static builder(factory)', it can be used like this:
```
chat.replyTemplate(new AttachmentTemplate(new ChatAttachment().readAttachment(JSON)));
```
or
```
chat.replyTemplate(new AttachmentTemplate(ChatAttachment.BuildAttachment(JSON)));
```

**Comment by LeeHyKu** [comment]
or this:
```
chat.replyTemplate(ChatAttachment.fromJson(JSON).template) //get function
```

**Comment by storycraft** [comment]
There are planned improvements for attachments. Was supposed to be updated already. But delayed due to low priority for enhancements. The problem is that nested objects are too messy.

Current design
```typescript
new CustomAttachment(new CustomInfo(/*very long arguments*/), content);
```

Inner contents(AttachmentContent) can be improved like this
```typescript
new CustomAttachment({ message: 'link', type: CustomType.FEED, /* e.t.c. */ }, { /* contents */ });
```

This suggestion is unsafe because attachment counts, types are determined by chat type.
```typescript
chat.replyTemplate(ChatAttachment.fromJson(JSON).template);
```
