### ISSUE TITLE
on "chat" event cannot emit

### ISSUE THREAD

**Issue by punch5545** [storycraft/node-kakao#763]
**Describe the bug**
on "chat" event emitter cannot emit event when the chat type is REPLY and attachment is empty

**To Reproduce**

Sender
```ts
            let chat = new ChatBuilder().text(`대충 광고하는 텍스트`)
                .append(new ReplyContent({
                    type: 1,
                    logId: new Long(null),
                    prevLogId: new Long(null),
                    sender: { userId: new Long(null) },
                    sendAt: null,
                    messageId: null
            })).build(KnownChatType.REPLY);

            chat.attachment = null;  
            // chat.attachment = {}; // 위, 아래 둘다 전송 됨.
            channel.sendChat(chat);
```

Reciever
```ts
Global.node_client.on('chat', async (data, channel) => {
    console.log(data.chat);
    if (channel instanceof TalkOpenChannel) {
//        console.log("openchat");
//        console.log(data.chat);
    }
}
```

**Expected behavior**

Expected emitting chat event but It wasn't.

**Screenshots**

![image](https://user-images.githubusercontent.com/28100137/139088497-d12da361-42e3-4ca9-bbea-599f5d1403a4.png)
![image](https://user-images.githubusercontent.com/28100137/139088421-7db4634f-d148-483e-9562-5025e3caa478.png)

----- I can show the Log when I use .getChatListFrom(); method. -----

![image](https://user-images.githubusercontent.com/28100137/139089527-3b6e951a-bfc8-41a3-8d9f-f6d5ce6a5496.png)

---

**Comment by storycraft** [comment]
I cannot reproduce this issue. Also do not upload files containing abusive contents.

NodeKakao does not discard chat message with specific type or attachment. There is no such code doing that on MSG packet handling. It should emit error instead if it failed to process internally.

**Comment by lee-jox** [comment]
버전문제인가요. 동일하게 재현되었습니다.  sendChat 으로 전송 후 바로 나오지 않습니다. 후속적으로 입력을 받은 후 출력됩니다. sendChat 시 바로 메시지가 나오지 않습니다.

**Comment by punch5545** [comment]
> I cannot reproduce this issue. Also do not upload files containing abusive contents.
> 
> NodeKakao does not discard chat message with specific type or attachment. There is no such code doing that on MSG packet handling. It should emit error instead if it failed to process interally.


There's NO EXCEPTION RAISE when I surrounded code by try/catch block. even in emitter codes.

**Comment by kiwioverflow** [comment]
패킷상으로 아에 안던져주는거같은데...

코덱 부분의 headerArray에서도 관련 패킷이 안찍히는거같습니다.

**Comment by storycraft** [comment]
The issue is not caused by NodeKakao but by Official client server since the official client also have same issue.

The server does not send `MSG` packet when the chat is REPLY type without attachment. The official client sends `SYNCMSG` (syncChatList method equivalent) based on user interaction to sync missing chat messages explicitly. Due to this behaviour in official client the chat is inserted after awhile and it looks like it work as intended.

This issue cannot be fixed on library side.

**Comment by starlesssss** [comment]
chat.prevLogId might work for this, since it's not generated by client but received from server.

**Comment by holiday22** [comment]
답글 chat.type 을  막는 방법으로 가능할까요?

**Comment by kiwioverflow** [comment]
> @holiday22 답글 chat.type 을 막는 방법으로 가능할까요?

Nope.
As Storycraft explained earlier, if reply messages (Type 26) don't have attachment object, server does not send MSG packets to clients.

>Excerpts from  https://github.com/storycraft/node-kakao/issues/763#issuecomment-954402326 ...
The official client sends SYNCMSG (syncChatList method equivalent) based on user interaction to sync missing chat messages explicitly. Due to this behaviour in official client the chat is inserted after awhile and it looks like it work as intended.

The only way to get a message from Node-Kakao is to implement it similarly to an official client. This is not a library problem, but Kakao server problem. so it cannot be solved in our line.

**Comment by moa12gg** [comment]
channel.getChatListFrom()에도 뜨지 않던데 어떻게 하셨나요??


> ----- I can show the Log when I use .getChatListFrom(); method. -----
> 
> ![image](https://user-images.githubusercontent.com/28100137/139089527-3b6e951a-bfc8-41a3-8d9f-f6d5ce6a5496.png)

**Comment by punch5545** [comment]
> channel.getChatListFrom()에도 뜨지 않던데 어떻게 하셨나요??
> 
> > ----- I can show the Log when I use .getChatListFrom(); method. -----
> > ![image](https://user-images.githubusercontent.com/28100137/139089527-3b6e951a-bfc8-41a3-8d9f-f6d5ce6a5496.png)

```ts
channel.getChatListFrom(new Long(chatid));
```
